### ISSUE TITLE
Use configured parrot sites directory

### ISSUE THREAD

**Issue by anotherjames** [anotherjames/dotfiles#2]
https://github.com/anotherjames/dotfiles/blob/master/aliases.drushrc.php#L4

...or at least replace 'jameswilliams' with drush_get_username() (or something from within that)?!

**Comment by darthsteven** [comment]
Yeah, you might need to attempt to read the YAML config file within ~/parrot I suppose.

**Comment by anotherjames** [comment]
> ...or at least replace 'jameswilliams' with drush_get_username() (or something from within that)?!

Oh this bit is already done. So we now need to parse (or can we get away with a regex?) YAML.

**Comment by anotherjames** [comment]
Updated link to avoid confusion: https://github.com/anotherjames/dotfiles/blob/ff7e9df02a41377269f91bc1fc6b6aff8f18d6a7/aliases.drushrc.php#L11
This is now about using the configured _sites_ directory, rather than hardcoding to '.../parrot/sites'.

**Comment by anotherjames** [comment]
Using parrot is now unsupported. at least by me :)
